services:
  # frontend:
  #   image: react-dev
  #   build:
  #     context: frontend
  #   volumes:
  #     - ./frontend/src:/app/src
  #   ports:
  #     - 3000:3000

  db:
    image: postgres
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "hibernatedb"
      POSTGRES_USER: "hibernateuser"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5433:5432"
    networks:
      - db-back

  minio:
    image: minio/minio:latest
    command: server --address :9000 /data
    ports:
      - "9000:9000"  # MinIO API port
      - "9001:9001"  # MinIO Console port
    volumes:
      - minio_data:/data  # Persistent storage
    networks:
      - minio-back

  ollama-neuro:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - ollama-back

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
      - ollama-neuro
    networks:
      - ollama-back
      - db-back
      - minio-back

volumes:
  postgresql:
  minio_data:
  ollama:

networks:
  ollama-back:
    driver: bridge
  db-back:
    driver: bridge
  minio-back:
    driver: bridge
